title: 医疗数据分析作业作品集
description: 住院死亡风险预测分析项目展示
baseurl: ""
url: "http://ZhangHuiting123.github.io"
markdown: kramdown
permalink: /:title/
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
defaults:
  - scope:
      path: ""
      type: portfolio
    values:

      layout: "portfolio"
